<!-- DTD - Ejercicio 1-1 - Números -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE numeros [
  <!ELEMENT numeros (numero)> 
  <!-- Crea un elemento número y luego lo registra --> 
  <!ELEMENT numero (#PCDATA)>
]>

<numeros>
  <numero>25</numero>
</numeros>

<!-- DTD - Ejercicio 1-2 - Letras --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE letras [
  <!ELEMENT letras (letra+)> <!-- Añadimos "letra+" para que permita la inclusión de mas de un elemento --> 
  <!ELEMENT letra (#PCDATA)>
]>

<letras>
  <letra>m</letra>
  <letra>uve doble</letra>
</letras>

<!-- DTD - Ejercicio 1-3 - Colores --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
  <!ELEMENT colores (ANY)> <!-- Se escribe ANY para anular cualquier comprobación -->
  <!ELEMENT color (#PCDATA)>  
]>

<colores>
  <color>azul marino</color>
  negro
  <color>amarillo</color>
</colores>

<!-- DTD - Ejercicio 1-4 - Flores --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flores [
  <!ELEMENT flores (flores*)> <!-- Modificamos de "flor+" a "flor*" para que no necesite --> 
  <!ELEMENT flor (#PCDATA)>
]>

<flores>
</flores>

<!-- DTD - Ejercicio 1-5 - Animales --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animales [
  <!ELEMENT animales (perro*, gato*)>
  <!ELEMENT animal (#PCDATA)>
  <!ELEMENT perro (#PCDATA)>
  <!ELEMENT gato (#PCDATA)>
]>

<animales>
  <perro>Caniche</perro>
  <gato>Siamés</gato>
</animales>

<!-- DTD - Ejercicio 1-6 - Escritores. NO SE PUEDE SOLUCIONAR--> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escritores [
  <!ELEMENT escritores (ANY*)> <!-- Se escribe ANY para anular cualquier comprobación -->
  <!ELEMENT escritor (nombre, nacimiento)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT nacimiento (#PCDATA)>
  
]>

<escritores>
  <escritor>
    <nombre>Mario Vargas Llosa</nombre>
    <nacimiento>28 de marzo de 1936</nacimiento>
  </escritor>
  <escritor>
    <nacimiento>1 de abril de 1929</nacimiento>
    <nombre>Milan Kundera</nombre>
  </escritor>
</escritores>

<!-- DTD - Ejercicio 1-7 - Músicos -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicos [
  <!ELEMENT musicos (musico*)>
  <!ELEMENT musico ((nombre, apodo), fechaNacimiento)> <!-- Cambiamos "|" por "," -->
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apodo (#PCDATA)>
  <!ELEMENT fechaNacimiento (#PCDATA)>
]>

<musicos>
  <musico>
    <nombre>Antonio Vivaldi</nombre>
    <apodo>El cura pelirrojillo</apodo>
    <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
  </musico>
  <musico>
    <nombre>Johann Sebastian Bach</nombre>
    <apodo>El viejo peluca</apodo>
    <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
  </musico>
</musicos>

<!-- DTD - Ejercicio 1-8 - Teléfonos de emergencia --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
  <!ELEMENT agenda (contacto*)>
  <!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil*, telefonoFijo*)> <!-- Habilitamos un tercer campo para poder añadir el teléfono fijo, y permitimos que se impriman cuantos telefonos moviles y fijos queremos --> 
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT telefonoFijo (#PCDATA)>
  <!ELEMENT telefonoMovil (#PCDATA)>
]>

<agenda>
  <contacto>
    <nombre>Ayuntamiento</nombre>
    <telefonoFijo>010</telefonoFijo>
  </contacto>
  <contacto>
    <nombre>Emergencias</nombre>
    <telefonoFijo>112 (Unión Europea)</telefonoFijo>
    <telefonoMovil>Desconocido</telefonoMovil>
    <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
  </contacto>
</agenda>

<!-- DTD - Ejercicio 1-9 - El sistema solar -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemaSolar [
  <!ELEMENT sistemaSolar (cuerpo*, asteroide)> 
  <!ELEMENT cuerpo (planeta,satelite)>
  <!ELEMENT asteroides (asteroide)>
  <!ELEMENT planeta (#PCDATA)>
  <!ELEMENT satelite (#PCDATA)>
  <!ELEMENT asteroide (#PCDATA)>
]>

<sistemaSolar>
  <cuerpo>
    <planeta>Tierra</planeta>
    <satelite>Luna</satelite>
  </cuerpo>
  <asteroide>Ceres</asteroide>
</sistemaSolar>