<!-- DTD - Ejercicio 2-1 - Marcadores -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [ 
  <!ELEMENT marcadores (marcador+)>
  <!ELEMENT marcador (nombre, uri)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT uri (#PCDATA)>    
]>

<!-- ERROR: sustituir "favoritos" por "marcadores" y agregar más de una instancia para "marcador" --> 


<marcadores>
  <marcador>
    <nombre>W3C</nombre>
    <uri>http://www.w3.org/</uri>
  </marcador>
  <marcador>
    <nombre>Web Hypertext Application Technology Working Group (WHATWG)</nombre>
    <uri>http://www.whatwg.org/</uri>
  </marcador>
</marcadores>

<!-- DTD - Ejercicio 2-2 - Efemérides -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE efemerides [
  <!ELEMENT efemerides (efemeride+)>
  <!ELEMENT efemeride (fecha, hecho)>
  <!ELEMENT fecha (#PCDATA) >
  <!ELEMENT hecho (#PCDATA) >
]>

<!-- AGREGAR: PCDATA en "fecha" y "hecho" y capacitar "efemeride" para ser instanciado en varias ocasiones --> 

<efemerides>
  <efemeride>
    <fecha>20 de julio de 1969</fecha>
    <hecho>Llegada del hombre a la Luna</hecho>
  </efemeride>
  <efemeride>
    <fecha>12 de octubre de 1492</fecha>
    <hecho>Llegada de Colón a América</hecho>
  </efemeride>
  <efemeride>
    <fecha>6 de abril de 1909</fecha>
    <hecho>llegada de Robert Peary al Polo Norte</hecho>
  </efemeride>
</efemerides>

<!-- DTD - Ejercicio 2-3 - Aeropuertos -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos [
  <!ELEMENT aeropuertos (aeropuerto*)>
  <!ELEMENT aeropuerto (nombre, cerrado?)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT cerrado (#PCDATA)>
]>

<!-- Configuramos "cerrado" para que pueda estar o no presente "?"  --> 

<aeropuertos>
  <aeropuerto>
    <nombre>Berlín Schönefeld (SFX)</nombre>
  </aeropuerto>
  <aeropuerto>
    <nombre>Berlín Tempelhof (THF)</nombre>
    <cerrado />
 </aeropuerto>
</aeropuertos>

<!-- DTD - Ejercicio 2-4 - Vuelos --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vuelos [
  <!ELEMENT vuelos (vuelo*)>
  <!ELEMENT vuelo (origen?, destino?, destino?, origen?)>
  <!ELEMENT origen (#PCDATA)>
  <!ELEMENT destino (#PCDATA)>
]>

<!---------- 
Asociar la posibilidad a que existe el desorden, de modo que pueda permitirse : 
origen, destino
destino, origen
------------->

<vuelos>
  <vuelo>
    <origen>Valencia (VLC)</origen>
    <destino>Londres Heathrow (LHR)</destino>
  </vuelo>
  <vuelo>
    <destino>Berlín Schönefeld (SFX)</destino>
    <origen>París Charles de Gaulle (CDG)</origen>
  </vuelo>
</vuelos>

<!-- DTD - Ejercicio 2-5 - Reyes españoles --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reyesEspañoles [
  <!ELEMENT reyesEspañoles (rey*, reina*, rey*)>
  <!ELEMENT rey (nombre, padre, madre)>
  <!ELEMENT reina (nombre, padre, madre)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT padre (#PCDATA)>
  <!ELEMENT madre (#PCDATA)>

]>

<!-- Falta el ELEMENT reina, y existe un fallo en la organización del esquema resyesEspañoles, al que hay que agregarle "rey*") --> 

<reyesEspañoles>
  <rey>
    <nombre>Felipe III</nombre>
    <padre>Felipe II</padre>
    <madre>Ana de Austria</madre>
  </rey>
  <reina>
    <nombre>Juana la Loca</nombre>
    <padre>Fernando el Católico</padre>
    <madre>Isabel la Católica</madre>
  </reina>
  <rey>
    <nombre>Carlos I</nombre>
    <padre>Felipe el Hermoso</padre>
    <madre>Juan la Loca</madre>
  </rey>
</reyesEspañoles>

<!-- DTD - Ejercicio 2-6 - Países --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
  <!ELEMENT paises (pais*)>
  <!ELEMENT pais (nombre, unionEuropea?, otan?)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT unionEuropea EMPTY>
  <!ELEMENT otan EMPTY>
]>

<!-- El  nombre debe almacenarse, por lo que se le asigna (#PCDATA), así también, debe agregarse el modificador "?" a unionEuropea y otan -->

<paises>
  <pais>
    <nombre>España</nombre>
    <unionEuropea />
    <otan />
  </pais>
  <pais>
    <nombre>Noruega</nombre>
    <otan />
  </pais>
  <pais>
    <nombre>Austria</nombre>
    <unionEuropea />
  </pais>
</paises>

<!-- DTD - Ejercicio 2-7 - Códigos de colores --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
  <!ELEMENT colores (color*)>
  <!ELEMENT color (nombreSvg, codigo) >
  <!ELEMENT codigo (rgb | cmyk) >
  <!ELEMENT nombreSvg (#PCDATA)>
  <!ELEMENT rgb (#PCDATA)>
  <!ELEMENT cmyk (#PCDATA)>
]>

<!-- Se introduce el elemento COLOR de los cuales subsisten nombreSvg y codigo.
A su vez, código puede ser cmyk o rgb, pero no los dos a la vez --> 

<colores>
  <color>
    <nombreSvg>Purple</nombreSvg>
    <codigo>
      <rgb>#800080</rgb>
    </codigo>
  </color>
  <color>
    <nombreSvg>Purple</nombreSvg>
    <codigo>
      <cmyk>#00FF007F</cmyk>
    </codigo>
  </color>
</colores>

<!-- DTD - Ejercicio 2-8 - Contabilidad --> 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
  <!ELEMENT contabilidad (apunte*)>
  <!ELEMENT apunte ((ingreso | gasto)*, fecha, cantidad, concepto)>
  <!ELEMENT fecha (#PCDATA)>
  <!ELEMENT cantidad (#PCDATA)>
  <!ELEMENT concepto (#PCDATA)>
  <!ELEMENT ingreso EMPTY > 
  <!ELEMENT gasto EMPTY >
]>

<!-- debe introducirse el apunte*, para que albergue varias etiquetas de apunte 
primeramente, apunte debe registrar tantos ingresos o gastos como sea posible - aunque no sería necesario (*) -, junto
con la fecha, cantidad y concepto. 
Los elementos ingresos y gasto no guardan información, por lo que quedarán como EMPTY. Esto no es necesario para 
que el DTD sea válido. --> 


<contabilidad>
  <apunte>
    <ingreso />
    <fecha>24 de febrero de 2011</fecha>
    <cantidad>1800,00 €</cantidad>
    <concepto>Salario</concepto>
  </apunte>
  <apunte>
    <gasto />
    <fecha>28 de febrero de 2011</fecha>
    <cantidad>74,25 €</cantidad>
    <concepto>Recibo luz</concepto>
  </apunte>
</contabilidad>

<!-- DTD - Ejercicio 2-9 - Mensajes --> 

<!DOCTYPE mensajes [
  <!ELEMENT mensajes (mensaje*)>
  <!ELEMENT mensaje (de, para, hora, texto)>
    <!ELEMENT texto (#PCDATA | strong)*>
   <!ELEMENT de (#PCDATA)>
  <!ELEMENT para (#PCDATA)>
  <!ELEMENT hora (#PCDATA)>
  <!ELEMENT strong (#PCDATA)>
]>

<!-- El elemento TEXTO debe alternar tanto TEXTO como etiquetas strong, y esto se hace con un "or" PCDATA# (texto) como strong (etiqueta) -->

<mensajes>
  <mensaje>
    <de>Pepe (pepe@example.com)</de>
    <para>Juan (juan@example.com)</para>
    <hora>28/02/2011 17:48:23,61</hora>
    <texto>¿Hola, Juan, qué haces?</texto>
  </mensaje>
  <mensaje>
    <de>Juan (juan@example.com)</de>
    <para>Pepe (pepe@example.com)</para>
    <hora>28/02/2011 17:54:20,87</hora>
    <texto>Aquí, aprendiendo <strong>XML</strong></texto>
  </mensaje>
</mensajes>
